[package]
name = "megaswap-faucet"
version = "0.1.0"
edition = "2024"

[dependencies]
pinocchio = { version = "0.11.2", features = ["account-resize"] }
pinocchio-associated-token-account = "0.4.0"
pinocchio-log = "0.5.1"
pinocchio-pubkey = "0.3.0"
pinocchio-system = "0.6.1"
pinocchio-token = "0.6.0"
pinocchio-token-2022 = "0.3.1"
solana-account-view = "2.0.0"
solana-address = { version = "2.6.1", features = ["curve25519"] }

[features]
default = []
std = []
no-entrypoint = []

[lib]
crate-type = ["lib", "cdylib"]
